In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('StudentsPerformance.csv')

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
columns = ['gender', 'race/ethnicity', 'parental level of education',
           'lunch', 'test preparation course']

for col in columns:
    df[col] = df[col].str.strip().str.lower()
df[columns].head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course
0,female,group b,bachelor's degree,standard,none
1,female,group c,some college,standard,completed
2,female,group b,master's degree,standard,none
3,male,group a,associate's degree,free/reduced,none
4,male,group c,some college,standard,none

In [7]:
scores = ['math score', 'reading score', 'writing score']

for col in scores:
    print(col, "Mean =", df[col].mean())

math score Mean = 66.089
reading score Mean = 69.169
writing score Mean = 68.054

In [8]:
for col in scores:
    print(col, "Median =", df[col].median())

math score Median = 66.0
reading score Median = 70.0
writing score Median = 69.0

In [9]:
for col in scores:
    print(col, "Standard Deviation =", df[col].std())

math score Standard Deviation = 15.163080096009468
reading score Standard Deviation = 14.60019193725222
writing score Standard Deviation = 15.195657010869642

In [10]:
for col in scores:
    print(col)
    print("Q1 =", df[col].quantile(0.25))
    print("Q2 =", df[col].quantile(0.50))
    print("Q3 =", df[col].quantile(0.75))

math score
Q1 = 57.0
Q2 = 66.0
Q3 = 77.0
reading score
Q1 = 59.0
Q2 = 70.0
Q3 = 79.0
writing score
Q1 = 57.75
Q2 = 69.0
Q3 = 79.0